// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:document_manager/utils/dotenv_util.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: DotenvUtil.apiKeyWeb,
    appId: DotenvUtil.appIdWeb,
    messagingSenderId: DotenvUtil.messagingSenderId,
    projectId: 'resukuru-mobile',
    authDomain: 'resukuru-mobile.firebaseapp.com',
    storageBucket: 'resukuru-mobile.appspot.com',
    measurementId: 'G-HD0RN2EM5F',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: DotenvUtil.apiKeyAndroid,
    appId: DotenvUtil.appIdAndroid,
    messagingSenderId: DotenvUtil.messagingSenderId,
    projectId: 'resukuru-mobile',
    storageBucket: 'resukuru-mobile.appspot.com',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: DotenvUtil.apiKeyIOS,
    appId: DotenvUtil.appIdIOS,
    messagingSenderId: DotenvUtil.messagingSenderId,
    projectId: 'resukuru-mobile',
    storageBucket: 'resukuru-mobile.appspot.com',
    iosBundleId: 'com.example.documentManager',
  );
}
